# Generated by Django 5.0.2 on 2024-02-15 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_users_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='users',
        ),
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'data'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name_plural': 'users'},
        ),
    ]
