# Generated by Django 5.0.2 on 2024-03-14 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_data_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'dat'},
        ),
    ]
