# Generated by Django 5.0.2 on 2024-03-14 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_data_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='data',
            options={'verbose_name_plural': 'data'},
        ),
    ]
