# Generated by Django 5.0.2 on 2024-03-07 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_menu_food_id_alter_menu_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='food_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
    ]
