# Generated by Django 5.0.2 on 2024-03-07 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_menu_food_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='userid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.users'),
        ),
    ]
