# Generated by Django 5.0.2 on 2024-03-07 15:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_data_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='userid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users'),
        ),
    ]
